# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/llms-txt',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/llms-txt',
                'lib_path': 'llms_txt'},
  'syms': { 'llms_txt.core': { 'llms_txt.core.Doc': ('core.html#doc', 'llms_txt/core.py'),
                               'llms_txt.core.Section': ('core.html#section', 'llms_txt/core.py'),
                               'llms_txt.core._opt_re': ('core.html#_opt_re', 'llms_txt/core.py'),
                               'llms_txt.core._parse_llms_txt': ('core.html#_parse_llms_txt', 'llms_txt/core.py'),
                               'llms_txt.core._parse_section': ('core.html#_parse_section', 'llms_txt/core.py'),
                               'llms_txt.core._split_on_h2': ('core.html#_split_on_h2', 'llms_txt/core.py'),
                               'llms_txt.core.get_sizes': ('core.html#get_sizes', 'llms_txt/core.py'),
                               'llms_txt.core.llms_txt2ctx': ('core.html#llms_txt2ctx', 'llms_txt/core.py'),
                               'llms_txt.core.mk_ctx': ('core.html#mk_ctx', 'llms_txt/core.py'),
                               'llms_txt.core.parse_llms_file': ('core.html#parse_llms_file', 'llms_txt/core.py')}}}
